CREATE TABLE IF NOT EXISTS camps (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location_name VARCHAR(255),
    address TEXT,
    latitude DOUBLE,
    longitude DOUBLE,
    location_accuracy DOUBLE,
    contact_number VARCHAR(50),
    officer_name VARCHAR(255),
    officer_uid VARCHAR(255),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_camps_active (active),
    INDEX idx_camps_officer_uid (officer_uid)
);

CREATE TABLE IF NOT EXISTS normal_records (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT,
    photo_url TEXT,
    camp_id VARCHAR(36),
    camp_name VARCHAR(255),
    officer_uid VARCHAR(255),
    officer_name VARCHAR(255),
    officer_contact VARCHAR(255),
    status VARCHAR(50) DEFAULT 'AT_CAMP',
    additional_details TEXT,
    found_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_normal_name (name),
    INDEX idx_normal_camp_id (camp_id),
    INDEX idx_normal_status (status),
    INDEX idx_normal_created_at (created_at),
    FOREIGN KEY (camp_id) REFERENCES camps(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS critical_records (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT,
    photo_url TEXT,
    clothing_photo_url TEXT,
    last_known_clothing VARCHAR(500),
    camp_id VARCHAR(36),
    camp_name VARCHAR(255),
    officer_uid VARCHAR(255),
    officer_name VARCHAR(255),
    officer_contact VARCHAR(255),
    found_location VARCHAR(500),
    found_latitude DOUBLE,
    found_longitude DOUBLE,
    additional_details TEXT,
    status VARCHAR(50) DEFAULT 'UNIDENTIFIED',
    found_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_critical_name (name),
    INDEX idx_critical_camp_id (camp_id),
    INDEX idx_critical_status (status),
    INDEX idx_critical_created_at (created_at),
    FOREIGN KEY (camp_id) REFERENCES camps(id) ON DELETE SET NULL
);
